name: dsci532
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=25.0
  - python=3.11.11
  - wheel=0.45.1
  - pip:
    - dash==2.18.2
    - ipykernel==6.29.5
    - ipython==8.32.0
    - notebook==7.3.2
    - pandas==2.2.3
    - ucimlrepo==0.0.7
